# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses:
      - 10.7.23.43/16
      gateway4: 10.7.0.101
      nameservers:
        addresses:
        - 10.7.0.101
  version: 2
