version: '3'
services:
  zabbix-postgress:
    image: oksesaneka22/zabbix:zabbix-postgres
    container_name: zabbix-postgres
    networks:
      - zabbix-net
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./var/lib/zabbix/timezone:/etc/timezone:ro
      - ./var/lib/zabbix/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
  zabbix-server:
    image: oksesaneka22/zabbix:zabbix-server
    container_name: zabbix-server
    networks:
      - zabbix-net
    volumes:
      - /var/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/timezone:/etc/timezone:ro
      - /var/lib/zabbix/localtime:/etc/localtime:ro
    ports:
      - "10051:10051"
      - "161:161"
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
  zabbix-web:
    image: oksesaneka22/zabbix:zabbix-web
    container_name: zabbix-web
    networks:
      - zabbix-net
    volumes:
      - ./var/lib/zabbix/timezone:/etc/timezone:ro
      - ./var/lib/zabbix/localtime:/etc/localtime:ro
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - DB_SERVER_HOST=zabbix-postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Kiev
networks:
  zabbix-net:
    driver: bridge
